### ISSUE TITLE
When I move a folder to a new workspace, two workspaces are created.

### ISSUE THREAD

**Issue by brettin** [PATRIC3/p3_web#469]
I decide that I want to make an existing folder sharable in a new workspace. I select the folder ("New Folder") then select move. This gives me what appears the ability to create a new workspace and move the folder in one operation, nice. However, I specified "New Workspace" in the box and this resulted in two new workspaces, with the one named "New Workspace" and one named "New Folder".

![image](https://user-images.githubusercontent.com/991769/27921769-75705aa4-623e-11e7-81e5-60748b017aa5.png)

![image](https://user-images.githubusercontent.com/991769/27921806-9377e814-623e-11e7-9744-4bff99f3f38d.png)

**Comment by nconrad** [comment]
Yeah, so I saw Rebecca tried to do the same thing today...so we can deem this an UX issue.

It sounds like you didn't deselect or hit enter to create the new workspace, and *then* select that new workspace.  If you don't do this, what will happen is the workspace will be created because you hit "ok" (because the textbox lost focus), and your data will also be moved to the directory you are currently viewing (assuming you haven't selected anything).   I will think about ways to remedy this, but probably the best way would be to have the new workspace/folder button result in another dialog, instead of allowing in-editing.
